blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('',views.HomeView,name="home"),
    path('about/',views.AboutView,name="about"),
    path('contact/',views.ContactView,name="contact"),
    path('post/<slug:pk>',views.PostView,name="post"),
    path('apply-form/',views.ApplyFormView,name="applyform")
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('',include('authentication.urls')),
    path('editor/',include('editor.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

editor/urls.py
from django.urls import path
from editor import views

urlpatterns = [
    path('login/',views.LoginViews,name="editor_login"),
    path("logout/",views.logoutView,name="logout_editor"),
    path('dashboard/',views.dashboardView,name="dashboard"),
    path('add-blog/',views.AddBlogView,name="addblog"),
    path('edit-blog/<int:id>/',views.editPostView,name="edit-blog"),
    path('delete-blog/<int:id>/',views.deletePostView,name="delete-blog"),
]

blog/models.py
from django.db import models
from tinymce.models import HTMLField
from authentication.models import User

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=200)
    message = models.TextField()
    
    def __str__(self):
        return self.name
    

class Blog(models.Model):
    title = models.CharField(max_length=200)
    subtitle = models.TextField(max_length=400, null=True,blank=True)
    slug = models.SlugField(max_length=200,unique=True)
    post = HTMLField()
    status = models.BooleanField(help_text="Check For Active else Inactive",default=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE,limit_choices_to={'is_staff': True})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self) -> str:
        return self.title
    
class EditorForm(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,limit_choices_to={'is_staff': False})
    subject = models.CharField(max_length=200)
    message = models.TextField(max_length=550)
    portfolio_url = models.URLField(max_length=500, verbose_name="Any URL", null=True, blank=True)
    resume = models.ImageField(upload_to='resume/',null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.subject

editor/models.py
from django.db import models

# Create your models here.

editor/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from .form import EditorAuth, BlogCreateForm
from django.contrib.auth.decorators import login_required
from blog.models import Blog
from django.template.defaultfilters import slugify

# Create your views here.
def LoginViews(request):
    fm = EditorAuth()
    if request.method == "POST":
        fm = EditorAuth(request,data=request.POST)
        
        if fm.is_valid():
            username = fm.cleaned_data['username']
            pwd = fm.cleaned_data['password']
            user = authenticate(username=username,password=pwd)
            if user is not None:
                login(request,user)
                return redirect("dashboard")
    return render(request,'editor/auth/login.html',{'form':fm})


@login_required(login_url="editor_login")
def dashboardView(request):
    user = request.user
    if user.is_editor:
        blogs = Blog.objects.filter(created_by=user).order_by('-id')
    else:
        blogs = Blog.objects.all().order_by('-id')
    
    fname = user.first_name
    group = user.groups.all()
    return render(request,'editor/home/dashboard.html',{'blogs':blogs,'group':group,'full_name':fname})

@login_required(login_url="editor_login")
def AddBlogView(request):
    fm = BlogCreateForm()
    if request.method == "POST":
        fm = BlogCreateForm(request.POST)
        if fm.is_valid():
            title = fm.cleaned_data['title']
            subtitle = fm.cleaned_data['subtitle']
            post = fm.cleaned_data['post']
            status = fm.cleaned_data['status']
            
            postc = Blog(title=title,slug=slugify(title),subtitle=subtitle,post=post,status=False,created_by=request.user)
            postc.save()
            return redirect("dashboard")
            
    return render(request,'editor/home/add-blog.html',{'form':fm})
    
@login_required(login_url="editor_login")
def editPostView(request,id):
    pi = Blog.objects.get(pk=id)
    fm = BlogCreateForm(instance=pi)
    if request.method == "POST":
        fm = BlogCreateForm(request.POST,instance=pi)
        if fm.is_valid():
            fm.save()
            return redirect("dashboard")
    return render(request,'editor/home/edit-blog.html',{'form':fm})


def deletePostView(request,id):
    if request.method == "GET":
        Blog.objects.get(id=id).delete()
    return redirect("dashboard")
    


def logoutView(request):
    logout(request)
    return redirect("editor_login")

templates/editor/home/add-blog.html
{% extends 'layout/editormain.html' %}

{% block body %}
{% load static %}
<div class="container mt-5 py-4">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-11 my-4">
            <div class="card my-5 p">
                <div class="card-header">
                    <h4 class="card-title">Add Blogs</h4>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group row">
                            {{form.as_p}}
                        </div>

                        <div class="form-group row">
                            <div>
                                <button type="submit" class="btn btn-primary btn-block">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% get_static_prefix %}tinymce/tinymce.min.js"></script>
<script src="{% get_static_prefix %}django_tinymce/init_tinymce.js"></script>

{% endblock %}

templates/editor/home/dashboard.html
{% extends 'layout/editormain.html' %}

{% block body %}

<div class="container mt-5 py-4">

    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-4 mt-5">
            <div class="card text-left ">
                <div class="card-body">
                    <h4 class="card-title">Name : {{full_name}}</h4>
                </div>
            </div>
        </div>
        <div class="col-4 mt-5">
            <div class="card text-left ">
                <div class="card-body">
                    <h4 class="card-title">Groups :
                        {% for grp in group %}
                        {{grp.name|default:'-'}}
                        {% endfor %}
                    </h4>
                </div>
            </div>
        </div>
        <div class="col-4 mt-5">
            <div class="card text-left ">
                <div class="card-body">
                    <h4 class="card-title">Total Post : {{blogs.count}}</h4>
                </div>
            </div>
        </div>
        <div class="col-md-11 my-4">
            <div class="card my-5">
                <div class="card-header" style="display: inline;">
                    <h4 class="card-title" style="display: initial;">All Blogs</h4>
                    <a href="{% url 'addblog' %}" style="float:right;" class="btn btn-success btn-sm"><i
                            class="fa fa-plus"></i> Add
                        Blog</a>
                </div>
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Title</th>
                                <th scope="col">Sub Title</th>
                                <th scope="col">Created At</th>
                                <th scope="col">Status</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if blogs %}


                            {% for blog in blogs %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{blog.title}}</td>
                                <td>{{blog.subtitle|default:'-'}}</td>
                                <td>{{blog.created_at|date:'F d, Y'}}</td>
                                <td>
                                    {% if blog.status %}
                                    <span class="text-success">Active </span>
                                    {% else %}
                                    <span class="text-danger">Inactive </span>
                                    {% endif %}
                                </td>
                                <td>
                                    <div style="display:inline-flex;">
                                        {% if perms.blog.change_blog %}
                                        <a href="{% url 'edit-blog' blog.pk %}" class="btn btn-warning btn-sm"
                                            title="Edit Blog"> <i class="fa fa-edit"></i></a>
                                        {% endif %}

                                        {% if perms.blog.delete_blog %}
                                        <a href="{% url 'delete-blog' blog.pk %}" class="btn btn-danger btn-sm"
                                            title="Delete Blog"> <i class="fa fa-trash"></i></a>
                                        {% endif %}


                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="6">No Blog Avalibale</td>
                            </tr>
                            {% endif %}



                        </tbody>
                    </table>
                </div>
            </div>



        </div>
    </div>
</div>
{% endblock body %}

templates/editor/home/edit-blog.html
{% extends 'layout/editormain.html' %}

{% block body %}
{% load static %}
<div class="container mt-5 py-4">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-11 my-4">
            <div class="card my-5 p">
                <div class="card-header">
                    <h4 class="card-title">Edit Blog</h4>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group row">
                            {{form}}
                        </div>
                        <div class="form-group row">
                            <div>
                                <button type="submit" class="btn btn-primary btn-block">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% get_static_prefix %}tinymce/tinymce.min.js"></script>
<script src="{% get_static_prefix %}django_tinymce/init_tinymce.js"></script>

{% endblock %}

templates/editor/home/profile.html
{% extends 'layout/editormain.html' %}

{% block body %}
{% load static %}
<div class="container mt-5 py-4">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-11 my-4">
            <div class="card my-5 p">
                <div class="card-header">
                    <h4 class="card-title">Profile</h4>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group row">
                            {{form.as_p}}
                        </div>

                        <div class="form-group row">
                            <div>
                                <button type="submit" class="btn btn-primary btn-block">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% get_static_prefix %}tinymce/tinymce.min.js"></script>
<script src="{% get_static_prefix %}django_tinymce/init_tinymce.js"></script>

{% endblock %}